In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("products_asos.csv", on_bad_lines='skip')

In [3]:
df.head(10)

,url,name,size,category,price,color,sku,description,images
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...
1,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...
2,https://www.asos.com/asos-design/asos-design-l...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...
3,https://www.asos.com/new-look/new-look-trench-...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...
4,https://www.asos.com/stradivarius/stradivarius...,Stradivarius double breasted wool coat in grey,"XS - UK 6,S - UK 8,M - UK 10,L - UK 12,XL - UK 14",Stradivarius double breasted wool coat in grey,59.99,GREY,123650194.0,[{'Product Details': 'Coats & Jackets by Strad...,['https://images.asos-media.com/products/strad...
5,https://www.asos.com/stradivarius/stradivarius...,Stradivarius double breasted wool coat in grey,"XS - UK 6,S - UK 8,M - UK 10,L - UK 12,XL - UK 14",Stradivarius double breasted wool coat in grey,59.99,GREY,123650194.0,[{'Product Details': 'Coats & Jackets by Strad...,['https://images.asos-media.com/products/strad...
6,https://www.asos.com/barneys-originals/barneys...,Stradivarius double breasted wool coat in grey,"XS - UK 6,S - UK 8,M - UK 10,L - UK 12,XL - UK 14",Stradivarius double breasted wool coat in grey,59.99,GREY,123650194.0,[{'Product Details': 'Coats & Jackets by Strad...,['https://images.asos-media.com/products/strad...
7,https://www.asos.com/stradivarius/stradivarius...,Stradivarius double breasted wool coat in grey,"XS - UK 6,S - UK 8,M - UK 10,L - UK 12,XL - UK 14",Stradivarius double breasted wool coat in grey,59.99,GREY,123650194.0,[{'Product Details': 'Coats & Jackets by Strad...,['https://images.asos-media.com/products/strad...
8,https://www.asos.com/asos-petite/asos-design-p...,JDY oversized trench coat in stone,"3XL - UK 18 - Out of stock,XS - UK 6,S - UK 8,...",JDY oversized trench coat in stone,45.00,STONE,125806824.0,[{'Product Details': 'Coats & Jackets by JDYLo...,['https://images.asos-media.com/products/jdy-o...
9,https://www.asos.com/jdy/jdy-oversized-trench-...,JDY oversized trench coat in stone,"3XL - UK 18 - Out of stock,XS - UK 6,S - UK 8,...",JDY oversized trench coat in stone,45.00,STONE,125806824.0,[{'Product Details': 'Coats & Jackets by JDYLo...,['https://images.asos-media.com/products/jdy-o...

In [4]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df = df.dropna(subset=['price'])

In [5]:
print(f'Data Loaded : {len(df)} rows')
df.head(5)

Data Loaded : 18378 rows

,url,name,size,category,price,color,sku,description,images
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...
1,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...
2,https://www.asos.com/asos-design/asos-design-l...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...
3,https://www.asos.com/new-look/new-look-trench-...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...
4,https://www.asos.com/stradivarius/stradivarius...,Stradivarius double breasted wool coat in grey,"XS - UK 6,S - UK 8,M - UK 10,L - UK 12,XL - UK 14",Stradivarius double breasted wool coat in grey,59.99,GREY,123650194.0,[{'Product Details': 'Coats & Jackets by Strad...,['https://images.asos-media.com/products/strad...

# text splitting for consistency brand in column

In [6]:
df['description'] = df['description'].astype(str)
df['description']

0        [{'Product Details': 'Coats & Jackets by New L...
1        [{'Product Details': 'Coats & Jackets by New L...
2        [{'Product Details': 'Coats & Jackets by New L...
3        [{'Product Details': 'Coats & Jackets by New L...
4        [{'Product Details': 'Coats & Jackets by Strad...
                               ...
30840    [{'Product Details': 'Mini dress by Urban Revi...
30841    [{'Product Details': 'Dress by ASOS DESIGN Act...
30842    [{'Product Details': 'Dress by ASYOU Exclusive...
30843    [{'Product Details': 'Petite by Miss Selfridge...
30844    [{'Product Details': 'Dresses by & Other Stori...
Name: description, Length: 18378, dtype: object

In [7]:
def get_brand(text):
    if 'by ' in text:
        try:
            return text.split('by ')[1].split(' ')[0]
        except:
            return 'Unknown'
    return 'Unknown'

In [8]:
df["brand_raw"] = df["description"].apply(get_brand)

In [9]:
df

,url,name,size,category,price,color,sku,description,images,brand_raw
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,New
1,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,New
2,https://www.asos.com/asos-design/asos-design-l...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,New
3,https://www.asos.com/new-look/new-look-trench-...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,Neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,New
4,https://www.asos.com/stradivarius/stradivarius...,Stradivarius double breasted wool coat in grey,"XS - UK 6,S - UK 8,M - UK 10,L - UK 12,XL - UK 14",Stradivarius double breasted wool coat in grey,59.99,GREY,123650194.0,[{'Product Details': 'Coats & Jackets by Strad...,['https://images.asos-media.com/products/strad...,StradivariusJacket
...,...,...,...,...,...,...,...,...,...,...
30840,https://www.asos.com/urban-revivo/urban-revivo...,Urban Revivo square neck mini dress in floral ...,"XS - UK 6 - Out of stock,S - UK 8 - Out of sto...",Urban Revivo square neck mini dress in floral ...,44.00,Multi,116745746.0,[{'Product Details': 'Mini dress by Urban Revi...,['https://images.asos-media.com/products/urban...,Urban
30841,https://www.asos.com/asos-design/asos-design-l...,ASOS DESIGN long sleeve maxi t-shirt dress in ...,"UK 4 - Out of stock,UK 6 - Out of stock,UK 8 -...",ASOS DESIGN long sleeve maxi t-shirt dress in ...,24.00,Black,1444255.0,[{'Product Details': 'Dress by ASOS DESIGN Act...,['https://images.asos-media.com/products/asos-...,ASOS
30842,https://www.asos.com/asyou/asyou-layered-t-shi...,ASYOU layered t-shirt dress with focus graphic...,"UK 4 - Out of stock,UK 6,UK 8 - Out of stock,U...",ASYOU layered t-shirt dress with focus graphic...,22.99,Washed black,110783769.0,[{'Product Details': 'Dress by ASYOU Exclusive...,['https://images.asos-media.com/products/asyou...,ASYOU
30843,https://www.asos.com/miss-selfridge/miss-selfr...,Miss Selfridge Petite rib knit frill hem funne...,"UK 4 - Out of stock,UK 6 - Out of stock,UK 8 -...",Miss Selfridge Petite rib knit frill hem funne...,32.99,BLACK,116363729.0,[{'Product Details': 'Petite by Miss Selfridge...,['https://images.asos-media.com/products/miss-...,Miss
30844,https://www.asos.com/other-stories/other-stori...,& Other Stories plisse mesh midi dress in blac...,"XS - UK 4-6 - Out of stock,S - UK 8-10,M - UK ...",& Other Stories plisse mesh midi dress in blac...,65.00,Black and white,124159122.0,[{'Product Details': 'Dresses by & Other Stori...,['https://images.asos-media.com/products/other...,&

In [10]:
brand_category_count = df["brand_raw"].value_counts()
brand_category_count

brand_raw
ASOS                    4844
TopshopWelcome           711
New                      511
River                    467
Miss                     429
                        ...
FashionkillaWaist-up       1
OnlyIntroduce              1
TFNCDress                  1
OnlyFile                   1
YoursWash,                 1
Name: count, Length: 1654, dtype: int64

# Redefined category of brand use mapping

In [11]:
brand_map = {
    'New': 'New Look',
    'River': 'River Island',
    'Miss': 'Miss Selfridge',
    'TopshopWelcome': 'Topshop'
}

df['Brand'] = df['brand_raw'].map(brand_map).fillna(df['brand_raw'])

In [12]:
brand_count = df['Brand'].value_counts()
valid_brand = brand_count[brand_count > 5].index
df_clean = df[df['Brand'].isin(valid_brand)].copy()

print(df_clean["Brand"].value_counts().head(5))

Brand
ASOS              4844
Topshop           1017
New Look           511
River Island       467
Miss Selfridge     429
Name: count, dtype: int64

In [13]:
df_clean["size"].value_counts()

size
UK 4,UK 6,UK 8,UK 10,UK 12,UK 14,UK 16,UK 18                                                                                                                                                                            1865
UK 6,UK 8,UK 10,UK 12,UK 14,UK 16                                                                                                                                                                                        777
UK 16,UK 18,UK 20,UK 22,UK 24,UK 26,UK 28,UK 30                                                                                                                                                                          392
UK 6,UK 8,UK 10,UK 12,UK 14,UK 16,UK 18                                                                                                                                                                                  256
UK 18,UK 20,UK 22,UK 24,UK 26,UK 28                                                                                                                                                                                      255
                                                                                                                                                                                                                        ...
M - UK 10,L - UK 12,XL - UK 14,2XL - UK 16 - Out of stock                                                                                                                                                                  1
UK 4,UK 6,UK 8 - Out of stock,UK 10,UK 12 - Out of stock,UK 14 - Out of stock,UK 16 - Out of stock,UK 18 - Out of stock,UK 20 - Out of stock                                                                               1
UK 4,UK 6,UK 8 - Out of stock,UK 10 - Out of stock,UK 12 - Out of stock,UK 14,UK 16,UK 18,UK 20                                                                                                                            1
UK 16-18,UK 20-22,UK 24-26,UK 28-30,UK 32-34                                                                                                                                                                               1
UK 4 - Out of stock,UK 6,UK 8 - Out of stock,UK 10 - Out of stock,UK 12 - Out of stock,UK 14 - Out of stock,UK 16 - Out of stock,UK 18 - Out of stock,UK 20 - Out of stock,UK 22 - Out of stock,UK 24 - Out of stock       1
Name: count, Length: 3137, dtype: int64

# function to analyze stockouts

In [14]:
def calculate_phantom_revenue(size_str):
    if not isinstance(size_str, str):
        return 0, 0.0
    # split "UK-6, UK-8 - Out of stock" into list
    sizes = size_str.split(',')
    total_size = len(sizes)
    # Count how many items are out of stock
    out_of_stocks = size_str.count('Out of stock')
    # Calculate Rate
    rate = out_of_stocks / total_size if total_size > 0 else 0.0
    return out_of_stocks, rate

metrics = df_clean['size'].apply(lambda x: calculate_phantom_revenue(x))
df_clean["Stockout_Count"] = [x[0] for x in metrics]
df_clean["Stockout_Rate"] = [x[1] for x in metrics]

In [15]:
df_clean[["Stockout_Count", "Stockout_Rate"]].head(9)

    Stockout_Count  Stockout_Rate
0                1          0.125
1                1          0.125
2                1          0.125
3                1          0.125
4                0          0.000
5                0          0.000
6                0          0.000
7                0          0.000
10               0          0.000

In [16]:
# missing revenue cause of Out of stock
df_clean["Lost"] = df_clean["price"] * df_clean["Stockout_Count"]

In [17]:
cols = ["Brand", "name", "price", "Stockout_Count", "Lost"]
print(df_clean.sort_values(by='Lost', ascending=False).head(5)[cols])

         Brand                                               name  price  \
2941   Barbour               Barbour Beadnell wax jacket in black  219.0
21948  Topshop  Topshop premium real leather collared zip thro...  260.0
2715      ASOS  ASOS DESIGN premium real leather trench coat i...  220.0
15584     ASOS  ASOS EDITION geo embellished fringe plunge mid...  250.0
29838  Topshop           Topshop Baggy co-ord jeans in green cord   50.0

       Stockout_Count    Lost
2941                9  1971.0
21948               7  1820.0
2715                7  1540.0
15584               6  1500.0
29838              27  1350.0

In [18]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15899 entries, 0 to 30844
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             15899 non-null  object
 1   name            15899 non-null  object
 2   size            15899 non-null  object
 3   category        15899 non-null  object
 4   price           15899 non-null  float64
 5   color           15899 non-null  object
 6   sku             15899 non-null  float64
 7   description     15899 non-null  object
 8   images          15899 non-null  object
 9   brand_raw       15899 non-null  object
 10  Brand           15899 non-null  object
 11  Stockout_Count  15899 non-null  int64
 12  Stockout_Rate   15899 non-null  float64
 13  Lost            15899 non-null  float64
dtypes: float64(4), int64(1), object(9)
memory usage: 1.8+ MB

In [26]:
brand_strat = df_clean.groupby('Brand').agg({
    'price': 'mean',
    'Stockout_Rate': 'mean',
    'Lost': 'sum',
    'name': 'count'
}).reset_index()
brand_strat

             Brand       price  Stockout_Rate      Lost  name
0                    41.085000       0.519524   1401.50    10
1                &   85.598214       0.300762  26804.00   224
2              4th   41.750000       0.308333   2850.00    40
3          AFRMAll   75.142857       0.122449    396.00     7
4         AFRMPart   56.846154       0.010989     55.00    13
..             ...         ...            ...       ...   ...
333  YoursWaist-up   21.323333       0.412698    334.84     6
334      YoursYour   19.178750       0.467262    430.29     8
335         adidas   48.335938       0.225952  27508.00   384
336        ellesse   16.000000       0.309524    112.00     7
337         sister  118.346939       0.200292   5616.00    49

[338 rows x 5 columns]

In [ ]:
brand_strategy = brand_strat[brand_strat["name"] > 10]
plt.figure(figsize=(12, 8))
sns.scatterplot(
    data=brand_strat,
    x='price',
    y='Stockout_Rate',
    size='Lost',
    sizes=(50, 500),
    alpha=0.7,
    palette='viridis'
)

winner = brand_strategy[
    (brand_strategy['price'] > 40) &
    (brand_strategy['Stockout_Rate'] > 0.4)
]

for i in range(len(winner)):
    plt.text(
        winner.iloc[i]['price'] + 1,
        winner.iloc[i]['Stockout_Rate'],
        winner.iloc[i]['Brand'],
        # fontsize=12,
        # color='black',
        # weight='bold'
    )

plt.title('Brand Strategy Analysis')
plt.xlabel('Average Price')
plt.ylabel('Stockout Rate')
plt.axvline(x=40, color='red', linestyle='--')
plt.axvline(y=0.4, color='red', linestyle='--')
plt.show()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1840218215.py, line 15)